ALTER TABLE learning_paths
    ADD COLUMN test_type ENUM('LISTENING_AND_READING', 'SPEAKING', 'WRITING') NOT NULL DEFAULT 'LISTENING_AND_READING';

ALTER TABLE lessons
    MODIFY COLUMN level ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED') NOT NULL DEFAULT 'BEGINNER';
