ALTER TABLE test_sets
    ADD COLUMN type ENUM('LISTENING_AND_READING', 'SPEAKING', 'WRITING') NOT NULL DEFAULT 'LISTENING_AND_READING' AFTER status;

ALTER TABLE questions
    MODIFY COLUMN options JSON NULL, -- Allow NULL because S&W don't have multiple choice options
    MODIFY COLUMN correct_option CHAR (1) NULL; -- Allow NULL because there is no single correct character

ALTER TABLE user_answers
    ADD COLUMN answer_text TEXT AFTER answer,           -- Store full writing essays
    ADD COLUMN answer_audio_url VARCHAR(255) AFTER answer_text, -- Store Cloudinary URL for the user's Speaking recording
    ADD COLUMN feedback TEXT AFTER answer_audio_url; -- Store feedback generated by AI
